### ISSUE TITLE
Dual numbers can be implemented with 1 line in Mathematica

### ISSUE THREAD

**Issue by Anixx** [ssmit1986/DualNumbers#3]
This one:

`$Pre=MatrixFunction[Function[ε,#],{{0,0},{1,0}}]/.{{a_,b_},{0,a_}}->a+ε b /.{{a_,0},{b_,a_}}->a+ε b&;`

After this, most built-in functions work with dual numbers:

```
 I^ε

 Out= 1 + (I ε Pi)/2
```

**Comment by SjoerdSmitWolfram** [comment]
Thanks for the input. That's an interesting suggestion, but I doubt that this approach scales very well for the purpose of  automatic differentiation in programs. For example, it does not work with the [example](https://github.com/ssmit1986/DualNumbers#example) in the Readme document. Also: programming with `$Pre` isn't very robust, I would say.
